---
title: "Project Linear model"
author: "Charu Rajput"
date: "23/11/2021"
output:
  html_document: default
  pdf_document: default
---
## Linear Model
```{r}
library(dplyr)
library(missForest)
library(tidyr)
```

```{r}
# importing the dataset
data = read.csv('cleaned_dataset.csv')
str(data)
``` 

```{r}
# displaying the dataset
head(data,6)
View(data)
#Importing the necessary libraries
library(ggplot2)
library(dplyr)
library(tidyverse)
library(caret)
```
```{r}
# making a new dataset with the columns we feel can impact the total cost

sig_data = data[, c('num_passengers', 'toll_amount', 'distance','rate_code','Duration','total_amount')]
head(sig_data)

# Now generating the model summary in order to get the level of significance
set.seed(123)
dim(sig_data)
train_samples <- sig_data$total_amount %>%
createDataPartition(p=0.8,list=FALSE)
head(train_samples)
train <- sig_data[train_samples,]
test <- sig_data[-train_samples,]
### Now running the regression model against all the columns of the sig_data dataframs
model <- lm(total_amount~.,data=train)
summary(model)
```

```{r}
### Making predictions and assessing the model performance on the test data set
pred <- model %>% predict(test)
#print(pred)
```
### Assesing the precision of prediction by calculating RMSE and R2 value
```{r}
#model performance
RMSE <- RMSE(pred,test$total_amount)
RMSE

R2 <- R2(pred,test$total_amount)
R2
# The model has performed good as the R2 value is pretty close to 1
```
