---
title: "Project Descision trees"
author: "Sanjana Godiawala"
date: "23/11/2021"
output: html_document
---
## Decision Trees
```{r}
#install.packages("rpart.plot")

```

```{r}
# importing the dataset
data = read.csv('cleaned_dataset.csv')
str(data)
``` 

```{r}
# displaying the dataset
head(data,6)
View(data)
#Importing the necessary libraries
library(ggplot2)
library(dplyr)
library(tidyverse)
library(caret)
```

```{r}
# making a new dataset with the columns we feel can impact the total cost

sig_data = data[, c('num_passengers', 'toll_amount', 'distance','rate_code','Duration','total_amount')]
head(sig_data)

# Now generating the model summary in order to get the level of significance
set.seed(123)
dim(sig_data)
train_samples <- sig_data$total_amount %>%
createDataPartition(p=0.8,list=FALSE)
head(train_samples)
train <- sig_data[train_samples,]
test <- sig_data[-train_samples,]
```

```{r}
library(rpart)
library(rpart.plot)
train1 <- sample_frac(train,0.01)
fit <- rpart(total_amount~., data = train1)
rpart.plot(fit)

```

```{r}
test1 <- sample_frac(test,0.01)
predict <-predict(fit, test1)
RMSE <- RMSE(predict,test1$total_amount)
RMSE
R2 <- R2(predict,test1$total_amount)
R2
```